### PR TITLE
fix container stats to work with stream option true or false

### PR DESCRIPTION
**Pull request by beverts312**
isStream is hardcoded to true, so there is no way to get stats without streaming.
This small change resolves that while still allowing the default streaming functionality
Issue #255

### CODE REVIEW

**Comment by elyas-bhy** [comment]
@beverts312 Do you mind updating this PR against the current master branch?
You can then ping @apocas to merge it.

**Comment by beverts312** [comment]
@elyas-bhy done
@apocas Let me know if you need me to do anything else

**Comment by apocas** [comment]
I like the idea, but there's one thing that worries me.

Until now the options object only contains options that will be exclusively sent to docker, if Docker in the future creates an option called "stream"in this endpoint we will have a conflict.

The odds of this happening are very low and adding a new parameter to avoid is even nastier.

Any ideas?

**Comment by beverts312** [comment]
There currently is an option "stream" for this endpont [docs](https://docs.docker.com/engine/reference/api/docker_remote_api_v1.24/#/get-container-stats-based-on-resource-usage). We are leveraging this parameter to set the stream http option and the docker option which are both required to get a non-streaming response

**Comment by apocas** [comment]
Duh... using streams from day one of dockerode, that I forgot about this :)
:+1: 
Will ping when published.

**Comment by apocas** [comment]
Published in v2.3.1

**Pull request merged**
