### PR TITLE
adding 201 for swarm support

### PR DESCRIPTION
**Pull request by ekristen**
Swarm seems to return a 201 on success

### CODE REVIEW

**Comment by rmg** [comment]
Looks like #159 wasn't enough to cover all the docker/swarm differences... I hope they settle on a more consistent API between the two soon!

@ekristen have you checked to see if there are an other endpoints that need a similar adjustment?

**Comment by apocas** [comment]
Yeah you bet. Until there's a consistent API this will be a pain in the *ss.
Until now we have seen 200 from swarm, now also 201.

Technically we could accept all 2xx as OK, but then we could loose context from different 2xx codes.

So for now I think we just have do follow and adapt :/

**Comment by ekristen** [comment]
For reference: https://github.com/docker/swarm/issues/1326

**Comment by apocas** [comment]
I think we may close this one, since it was fixed on the swarm side.

**Pull request closed without merging**
