### PR TITLE
Enable stream input on loadImage

### PR DESCRIPTION
**Pull request by CollinEstes**
Also added loadImage test case.

### CODE REVIEW

**Comment by CollinEstes** [comment]
I am working with Dockerode to load images that have been saved via the 'docker save' command, via a stream from the tar file.  I noticed there was no test coverage for the docker.loadImage function so I created one and found the problem to be with the request not having "isStream: true".  I added it with the corresponding test.

**Comment by pcarranzav** [comment]
+1, this is really useful

**Comment by apocas** [comment]
:+1: 
Will ping when published.

**Comment by apocas** [comment]
Published in v2.2.9

**Pull request merged**
