### PR TITLE
Add importImage and its corresponding test.

### LINKED ISSUE #2: Importing images
Does this module support importing images? The docker remote api supports importing images from stdin so this could possibly be supported here.

https://github.com/dotcloud/docker/issues/349

``` bash
ID=$(docker run -d desired-image /bin/bash)
docker export $ID | gzip -c > desired-image.tgz
docker rm $ID
# copy desired-image.tgz to another machine
gzip -dc desired-image.tgz | docker import - desired-image
```

If this module supported the final import line from a stream that would be great

``` javascript
var Docker = require('dockerode')
var fs = require('fs')
var docker = new Docker({socketPath: '/var/run/docker.sock'})
var readStream = fs.createReadStream('./desired-image.tgz')

// pipe to new image here
var image = docker.importImage('foo')
readStream.pipe(image)
```

Another use case is building from a Dockerfile on stdin http://docs.docker.io/en/latest/api/docker_remote_api_v1.5/#build-an-image-from-dockerfile-via-stdin

``` javascript
var Docker = require('dockerode')
var docker = new Docker({socketPath: '/var/run/docker.sock'})
var fs = require('fs')
var readStream = fs.createReadStream('/path/to/Dockerfile')
var image = docker.buildFromDockerfile('foo')
readStream.pipe(image)
```

### PR DESCRIPTION
**Pull request by pcarranzav**
Fixes #2 
Also:
* Fix test for pull with followProgress and pause.
* Increase timeout in after() of the labelsAndFilters test.

### CODE REVIEW

**Comment by apocas** [comment]
What's the difference between importImage and https://github.com/apocas/dockerode/blob/master/lib/docker.js#L48 ?

**Comment by pcarranzav** [comment]
`createImage`, as far as I see, doesn't accept passing a tar file to import, as it doesn't pass a `file` to the modem. It seems like `createImage` would be used to create (pull) an image from an existing repo (i.e. using an image tag as in [the test](https://github.com/apocas/dockerode/blob/master/test/docker.js#L399), whereas `importImage` allows importing tarred directories (useful for creating base images). Also see #2. Unless there's something I'm missing, please correct me if so.

**Comment by pcarranzav** [comment]
(Another possibility would be to allow passing the file to the `createImage` function, but that would involve changing the function's signature)

**Comment by apocas** [comment]
I see, missed that, but now I'm confused between this and loadImage.
https://github.com/apocas/dockerode/blob/master/lib/docker.js#L79 from https://docs.docker.com/engine/reference/api/docker_remote_api_v1.21/#load-a-tarball-with-a-set-of-images-and-tags-into-docker

loadImage works with a different tarball format?

**Comment by petrosagg** [comment]
Yeah, loadImage expects a tar archive produced by docker save, which includes a nested tar archive for each later and also the docker image metadata. importImage just imports a raw filesystem archive into a docker layer and tags it

**Comment by apocas** [comment]
:+1:

**Comment by pcarranzav** [comment]
Thank you @apocas! Do you have an estimate for when this may be published?

**Comment by apocas** [comment]
Published in v2.2.9

**Comment by pcarranzav** [comment]
Brilliant, thanks!

**Pull request merged**
