### PR TITLE
container.attach openStdin bug fix

### PR DESCRIPTION
**Pull request by cravler**

### CODE REVIEW

**Comment by rmg** [comment]
Nice catch!

Feel free to ignore me, I have no authority here. I have a habit of reviewing every PR I see because that's what I do at work all day:
> The change looks good, but I'm unsure how you would ever notice this bug. Did it cause a problem for you? Or is it just something you noticed while reading the code? Maybe the commit message could include a clue as to how it is a bug?

**Comment by apocas** [comment]
I see one use case that may reveal this bug, which is specifying a "openstdin" default option for attach and not via parameter.

The attach defaultoption will be lost in the process :)

Nice catch :)

**Comment by apocas** [comment]
I will also verify the rest of the code base for similar situations before tonight's release.

**Comment by apocas** [comment]
Published v2.2.3

**Pull request merged**
