### PR TITLE
add test and examples for filtering by map

### PR DESCRIPTION
**Pull request by briceburg**
requires docker-modem 0.3

@apocas as promised,  tests and example usage for the updated querysting behavior. 

Many thanks for merging my PR and for this module :) It's a ton of fun to play with docker in node.

### CODE REVIEW

**Comment by apocas** [comment]
Test is already there :)
https://github.com/apocas/dockerode/blob/master/test/docker.js#L567

Same for example: https://github.com/apocas/dockerode/blob/master/examples/listContainers.js#L22

**Comment by apocas** [comment]
Already merged in https://github.com/apocas/dockerode/pull/204

**Comment by apocas** [comment]
And https://github.com/apocas/dockerode/pull/203

**Comment by briceburg** [comment]
@apocas 

It's hard to notice, but the test is acutally different. The test from #203 does not use a map, but a string.

See:

https://github.com/apocas/dockerode/pull/203/files#diff-df246c5a1e6641e63103bcae0fa4b6aaR569

versus

https://github.com/apocas/dockerode/pull/207/files#diff-df246c5a1e6641e63103bcae0fa4b6aaR580

ditto the example.

I wanted to wait until the PR that supported maps/objects was merged into docker-modem before submitting these.

~ Brice

**Comment by apocas** [comment]
Ah totally missed that!

**Pull request merged**
