### PR TITLE
Expose Container constructor

### PR DESCRIPTION
**Pull request by d6u**
So we can use bluebird's `Promise.promisifyAll`[1*] method like so:

``` javascript
var Promise = require('bluebird')
Promise.promisifyAll(Docker.Container.prototype)

// later on
Docker.createContainer(function(container) {
    container.startAsync().then(function () { ... }); // startAsync is one of the promisified methods
})
```

[1 - https://github.com/petkaantonov/bluebird/blob/master/API.md#promisepromisifyallobject-target--object-options---object](https://github.com/petkaantonov/bluebird/blob/master/API.md#promisepromisifyallobject-target--object-options---object)

### CODE REVIEW

**Comment by amitaibu** [comment]
@daiweilu I believe the result of this is https://github.com/daiweilu/Dockership , correct?

**Comment by daiweilu** [comment]
@amitaibu Not exactly, https://github.com/daiweilu/Dockership/blob/master/lib/promisified/docker-promisified.js is the file that convert Dockerode into promise style.

**Comment by amitaibu** [comment]
:+1:

**Comment by mattqs** [comment]
For convenience I made an npm package "dockerode-bluebird" https://www.npmjs.com/package/dockerode-bluebird using the info given here.

**Comment by apocas** [comment]
Awesome! There were a few people asking for this :+1:

**Comment by sheerun** [comment]
Please include promise interface into this repository. Promise-wrapping packages quickly become out of date...

**Comment by KristerV** [comment]
+1 sheerun. Why are callback still a thing...

**Comment by nwalters512** [comment]
I'd like to second this. All of the "wrapped" versions haven't been updated in over a year. Trying to do anything complex with this quickly leads to callback hell.

**Comment by apocas** [comment]
I will expose all the constructors to make all of you promise lovers happier :)

I'm not saying that what we have right now leads to a callback hell, I continue to say that really depends on the writer's habits, schools, patterns, taste, ...

Just want Dockerode to be a really good base structure to everyone :)

**Comment by apocas** [comment]
Here we go:
https://github.com/apocas/dockerode/commit/85852285910d2e7ed90fd530e71c1115f12e8789

Happy to announce that I implemented a promises based interface :)
Please comment and contribute, I really want feedback before even thinking on publishing it.

https://github.com/apocas/dockerode#promises-yet-to-be-published

**Comment by sheerun** [comment]
Looks fine to me :)

**Comment by apocas** [comment]
Feedback needed: https://github.com/apocas/dockerode/issues/339

**Pull request closed without merging**
