### PR TITLE
Support building image from multiple files

### PR DESCRIPTION
**Pull request by heroandtn3**
Example:

``` JavaScript
docker.buildImage({
  context: __dirname,
  src: ['Dockerfile', 'file1', 'file2']
}, {t: imageName}, function (err, response) {
  //...
});
```

If this PR is accepted, I will send another PR to support `src` as directories

Inspired by https://github.com/JoTrdl/grunt-dock

### CODE REVIEW

**Comment by apocas** [comment]
Initially I didn't see the purpose of this, since you could pack it outside dockerode and then feed it.

But every other day people are creating issues about how to create the tar file, which lead me thinking about this PR :)

**Comment by chamerling** [comment]
Hi @apocas,

Any chance to see this PR merged?
Thx

**Comment by apocas** [comment]
Let's merge this one :)

**Comment by heroandtn3** [comment]
Thanks, it's good to see the PR merged

**Pull request merged**
