### PR TITLE
Added update to Node functionality

### PR DESCRIPTION
**Pull request by DJBnjack**
Can be used as following:
```
var node = docker_remote.getNode(nodes[req.params.name].id);
    node.inspect((err,node_info) => {
        // Update node with new availability
        update = {
            version: node_info.Version.Index,
            Availability: availability,
            Role: "worker",
        };

        node.update(update, (err, data) => {
           // node is updated
        });

    });
```

### CODE REVIEW

**Comment by DJBnjack** [comment]
Interesting note here btw, the Docker API requires version (with small 'v'), Availability and Role:

> If Availability or Role are omitted, this returns an error. Any other field omitted resets the current value to either an empty value or the default cluster-wide value.
https://docs.docker.com/engine/api/v1.24/

**Comment by apocas** [comment]
👍 
Will ping when published :)

**Comment by DJBnjack** [comment]
Thanks!

**Comment by apocas** [comment]
Published in v2.3.2

**Pull request merged**
