### PR TITLE
Add support for pulling images by digests

### LINKED ISSUE #152: pull images by their hash and verify checksums
docker CLI supports pulling images by their sha256 and the command line looks like this:

`docker pull user/image@sha256:12345678abcdef...`

Using the same format in dockerode makes util.parseRepositoryTag() sad. :(

AFAIK this is a Docker Hub API v2 feature.

### PR DESCRIPTION
**Pull request by rail**
fixes #152

### CODE REVIEW

**Comment by apocas** [comment]
Awesome, thanks!

Will ping when published.

**Comment by rail** [comment]
\o/

**Comment by apocas** [comment]
Published in v2.2.0

**Comment by rail** [comment]
Thanks!

**Pull request merged**
